web:
  image: docker.io/avatarnewyork/dockerenv-apache:php71
  ports:
    - "8080:80"
  links:
    - db
  environment:
    POSTFIX_HOSTNAME: dev.avatarnewyork.com
db:
  image: docker.io/avatarnewyork/dockerenv-mysql:percona56
  ports:
    - "3366:3306"
    
