version: 2

jobs:
  build:
    docker:
      - image: docker.io/avatarnewyork/dockerenv-apache:php71
      - image: docker.io/avatarnewyork/dockerenv-mysql:percona56

    steps:
      
      - checkout

      - setup_remote_docker
      
      - run:
          name: Install Docker Compose (v1.2.0)
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      
      - run:
          name: Composer Up
          command: |
            docker-compose -f /root/project/.circleci/config/docker-compose2.yml up -d
