version: 1

general:
  branches:
    only:
      - stage
      - hotfix-circleci

machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"
  override:
    # docker-compose v1.2.0
    - curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
    - chmod +x ~/docker-compose
    - mkdir -p ~/docker
    # dockerenv-apache:$DOCKERENV_APACHE_TAG 
    - if [[ ! -e ~/docker/dockerenv_apache.tar ]]; then docker pull "docker.io/avatarnewyork/dockerenv-apache:$DOCKERENV_APACHE_TAG" && docker save "docker.io/avatarnewyork/dockerenv-apache:$DOCKERENV_APACHE_TAG" > ~/docker/dockerenv_apache.tar; else docker load -i ~/docker/dockerenv_apache.tar; fi
    # dockerenv-mysql:$DOCKERENV_MYSQL_TAG
    - if [[ ! -e ~/docker/dockerenv_mysql.tar ]]; then docker pull "docker.io/avatarnewyork/dockerenv-mysql:$DOCKERENV_MYSQL_TAG" && docker save "docker.io/avatarnewyork/dockerenv-mysql:$DOCKERENV_MYSQL_TAG" > ~/docker/dockerenv_mysql.tar; else docker load -i ~/docker/dockerenv_mysql.tar; fi
    # replace env vars for docker-compose.yml
    - ./circle/bin/docker-compose-helper.sh
    
test:
  override:
    # docker up
    - ~/docker-compose -f ~/$CIRCLE_PROJECT_REPONAME/circle/config/docker-compose.yml up -d
    # decrypt db if encrypted
    - if [[ -f ~/$CIRCLE_PROJECT_REPONAME/data/db.sql.gz.enc ]]; then openssl aes-256-cbc -k "$OPENSSL_PASS" -in ~/$CIRCLE_PROJECT_REPONAME/data/db.sql.gz.enc -out ~/$CIRCLE_PROJECT_REPONAME/data/db.sql.gz -d; fi;
    # import db (sleep needed)
    - sleep 40; zcat ~/$CIRCLE_PROJECT_REPONAME/data/db.sql.gz | mysql -uadmin --password='admin' -P3366 -h127.0.0.1 test
    # execute platform script (default drupal.sh)
    - if [[ -z "$PLATFORM_SCRIPT" ]]; then PLATFORM_SCRIPT="drupal.sh"; fi; ~/$CIRCLE_PROJECT_REPONAME/circle/bin/$PLATFORM_SCRIPT
    # ngrock tunnel
    - unzip -d ~/ ~/$CIRCLE_PROJECT_REPONAME/circle/files/ngrok_2.0.19_linux_amd64.zip
    - ~/ngrok authtoken $NGROK_TOKEN
    - ~/ngrok http -subdomain=$CIRCLE_SHA1 8080:
        background: true
    # Wait for application and ngrok to be ready
    - curl --retry 10 --retry-delay 10 -v https://$CIRCLE_SHA1.ngrok.io
    # Execute Ghost Inspector tests using the ngrok tunnel
    - curl "https://api.ghostinspector.com/v1/suites/$GHOST_SUITE_ID/execute/?apiKey=$GHOST_API_KEY&startUrl=https://$CIRCLE_SHA1.ngrok.io" > $CIRCLE_ARTIFACTS/ghostinspector.json
    - if [ $(grep -c '"passing":false' $CIRCLE_ARTIFACTS/ghostinspector.json) -ne 0 ]; then exit 1; fi

deployment:
  staging:
    branch:
      - stage
    commands:
      - ./circle/bin/deploy.sh
